### ISSUE TITLE
查询不准确

### ISSUE THREAD

**Issue by idiomer** [xizhicode/ahocorasick-python#1]
![image](https://user-images.githubusercontent.com/17400651/46243319-934d5700-c405-11e8-8afd-cf316742816f.png)

应该要查询到acdabd和bdf。

--------------------
看了下代码，是FAIL指针构建的时候有问题（受abc和abe的ab前缀影响），下图的else语句：
![image](https://user-images.githubusercontent.com/17400651/46243344-e0312d80-c405-11e8-93ba-411be89ce62b.png)

**Comment by dladmschd** [comment]
I love you Thank you 고마워 사랑해

**Comment by zhoukunpeng504** [comment]
已解决
`pip install ahocorasick-python==0.0.7`
结果就正常了

**Comment by zhoukunpeng504** [comment]
@idiomer @dladmschd
