### ISSUE TITLE
bug 查询漏查

### ISSUE THREAD

**Issue by shihuaxing** [xizhicode/ahocorasick-python#2]
152     ac = AhoCorasick('tes','es','s','te')
153     print(ac.search('test'))

返回的结果是
{'tes', 'es', 'te'}
s没有返回.

**Comment by zhoukunpeng504** [comment]
收到

**Comment by zhoukunpeng504** [comment]
已解决。 
`pip install ahocorasick-python==0.0.7 
`
然后结果就正常了。

**Comment by zhoukunpeng504** [comment]
@shihuaxing
