### ISSUE TITLE
3万个关键词，建树要2分钟？

### ISSUE THREAD

**Issue by FrankWork** [xizhicode/ahocorasick-python#5]

**Comment by zhoukunpeng504** [comment]
代码 + 词方便提供下么？   我看看能否优化下。

**Comment by tokitsu-kaze** [comment]
> 代码 + 词方便提供下么？ 我看看能否优化下。

老哥，node_append这个函数复杂度不对吧，正常的ac自动机增加一个keyword复杂度是O(len(keyword))，你这个最坏情况是不是会变成O(len(keyword)*len(self.words))啊？还有为什么keyword传进来要sort，建ac机跟keyword顺序没关系吧？

**Comment by zhoukunpeng504** [comment]
构建ac  为了增加查询准确度   比标准的ac自动机增加了很多逻辑， 这部分慢了些。   你可以用我提供的那个例子 对于标准ac 测试下。

**Comment by zhoukunpeng504** [comment]
关于性能问题，  你这边如果方便提供词的话。  我可以试着优化下。

**Comment by tokitsu-kaze** [comment]
> 构建ac 为了增加查询准确度 比标准的ac自动机增加了很多逻辑， 这部分慢了些。 你可以用我提供的那个例子 对于标准ac 测试下。

不是啊老哥，ac机不是本来就是准确查询吗...我建议你重新学一遍...
